name: Trigger auto deployment for container-app-u7ntp52s7t4zi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-u7ntp52s7t4zi-AutoDeployTrigger-73f6317d-fe76-4586-b1a4-510d80237690.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPU7NTP52S7T4ZI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPU7NTP52S7T4ZI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPU7NTP52S7T4ZI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: defaultacrcontainerregistry895f.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPU7NTP52S7T4ZI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPU7NTP52S7T4ZI_REGISTRY_PASSWORD }}
          containerAppName: container-app-u7ntp52s7t4zi
          resourceGroup: appspacesragappa07aa694
          imageToBuild: defaultacrcontainerregistry895f.azurecr.io/container-app-u7ntp52s7t4zi:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


